name: Vu Nguyen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13045912375673652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030706'
    - '#3f3221'
    - '#c2c9d3'
    - '#857460'
  brandStrength: 0.3125
  lightness: 0.8462673788890243
  saturation: 0.9977830115240067
  rhythmicContrast: 0.941189136588946
purpose: []
